project:
  type: website
  output-dir: docs

website:
  title: "Sky Qiu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: work.qmd
        text: Experience
      - href: teaching.qmd
        text: TA
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

