---
title: "Research"
---

## Publications

-   **Sky Qiu**, Charles Barr, Lauren Dang, Issa Dahabreh, Larry Han, Kajsa Kvist, Hana Lee, Andrew Mertens, Nerissa Nance, Lei Nie, Kara Rudolph, Xu Shi, Jens Tarp, Salina P. Waddy, Kenneth Wiley, Andy Wilson, Margot Lisa Jing Yann, Zhiwei Zhang, Tianyue Zhou, Maya Petersen & Mark van der Laan (2026). Considerations for the Integration of Randomized Controlled Trials and Real-World Data. *arXiv preprint.* [\[Paper\]](https://arxiv.org/abs/2604.10308)
-   **Sky Qiu**, Susan Gruber, Pamela A. Shaw, Brian D. Williamson & Mark J. van der Laan (2026). Efficient Targeted Maximum Likelihood Estimators for Two-Phase Design Problems. *arXiv preprint.* [\[Paper\]](https://arxiv.org/abs/2602.24131)
-   Hana Lee, **Sky Qiu**, Spencer Haupert, Gabriel K. Innes, Tristan Naumann, Demissie Alemayehu & Mark van der Laan (2026). Methodological and regulatory considerations for causal AI in drug development. *npj Digital Medicine*. [\[Paper\]](https://www.nature.com/articles/s41746-026-02477-w)
-   **Sky Qiu**, Jens Tarp, Andrew Mertens & Mark van der Laan (2025). An Estimator-Robust Design for Augmenting Randomized Controlled Trial with External Real-World Data. *arXiv preprint.* [\[Paper\]](https://arxiv.org/abs/2501.17835)
-   Mark van der Laan, **Sky Qiu** & Lars van der Laan (2024). Adaptive-TMLE for the Average Treatment Effect based on Randomized Controlled Trial Augmented with Real-World Data. *Journal of Causal Inference, 14(1), p.20240025.* [\[Paper\]](https://www.degruyterbrill.com/document/doi/10.1515/jci-2024-0025/html?srsltid=AfmBOoorlpzvLFJIqvI6G9Quez6vdw2ZrwTkJzAA4nyO_aKhj5SkkDHC)
-   Zachary Butzin-Dozier, **Sky Qiu**, Alan E Hubbard, Junming Shi & Mark van der Laan (2024). Highly adaptive LASSO: Machine learning that provides valid nonparametric inference in realistic models. *medRxiv preprint*. [\[Paper\]](https://www.medrxiv.org/content/10.1101/2024.10.18.24315778v1)
-   **Sky Qiu**, Alan Hubbard, Juan Pablo Gutiérrez, Ganesh Pimpale, Alturo Juárez-Flores, Rakesh Ghosh, Ivan Ascencio-Montiel & Stefano Bertozzi (2024). Estimating the effect of realistic improvements of metformin adherence on COVID-19 mortality using targeted machine learning. *Global Epidemiology*, 100142. [\[Paper\]](https://doi.org/10.1016/j.gloepi.2024.100142)
-   Toru Shirakawa, Yi Li, Yulun Wu, **Sky Qiu**, Yuxuan Li, Mingduo Zhao, Hiroyasu Iso & Mark van der Laan (2024). Longitudinal targeted minimum loss-based estimation with temporal-difference heterogeneous transformer. *International Conference on Machine Learning (ICML) 2024*. [\[Paper\]](https://arxiv.org/abs/2404.04399)

## Awards & Honors

-   Chin Long Chiang Award for Excellence in Biostatistics Research, 2025

-   Phi Beta Kappa Honor Society, 2021
